# Generated by Django 3.2 on 2023-06-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_invoice_id',
            field=models.TextField(blank=True, default=None),
        ),
    ]
